### ISSUE TITLE
Request for data

### ISSUE THREAD

**Issue by qkrguswn2401** [openspeech-team/openspeech#133]
# ❓ Questions & Help
Hi, I have sent requests for Kspon subword data. (https://github.com/openspeech-team/openspeech/tree/main/openspeech/datasets)
I have attached the screenshot of the approval.
Is there something I need to do more to get the data?

**Comment by upskyy** [comment]
We shared the data related to the Kspon subword.   
However, we will not be sharing it in the future. This is because if you specify the path you want, a file will be created at that location. Please refer to [link1](https://github.com/openspeech-team/openspeech/blob/main/openspeech/datasets/ksponspeech/lit_data_module.py#L68-L97) and [link2](https://github.com/openspeech-team/openspeech#training-examples).   
Thanks.
